services:  # Backend API Service
  - type: web
    name: campussync-backend-api
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
  # Frontend Web Service
  - type: web
    name: campussync-frontend
    runtime: static
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: campussync-backend-api
          type: web
          envVarKey: RENDER_EXTERNAL_URL
          append: /api
